# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' CCA in hdf5 data files
#'
#' Compute Canonical Correlation Analyses (CCA) in data stored in hdf5 data files, 
#' this function is a dummy versions using only c++ functions from common c++ API's 
#' and BigDataStatMeth library
#' 
#' @param filename, Character array, indicating the name of the file with data to 
#' perform computations
#' @param datasetX, Character array, indicating the input datasets to be used 
#' as X matrix
#' @param datasetY, Character array, indicating the input datasets to be used 
#' as Y vector
#' @param bcenter logical. If TRUE (default), the data is centered by 
#' subtracting the column means (ignoring NAs) of `x` from their corresponding 
#' columns. If FALSE, no centering is performed.
#' @param bscale. If TRUE, the data is scaled by dividing the (centered) 
#' columns of `x` by their standard deviations if `bcenter` is TRUE, or by the 
#' root mean square otherwise. If FALSE, no scaling is performed.
#' @param byrows logical if TRUE, centering is done by subtracting the rows 
#' means, util when working with hdf5 datasets stored 
#' in Row Major format.
#' @param overwrite, boolean if true, previous results in same location inside 
#' hdf5 will be overwritten.
#' @param threads optional parameter. Integer with numbers of threads to be used
#' @export
bdCCA_hdf5_rcpp <- function(filename, datasetX, datasetY, bcenter, bscale, overwrite, threads = NULL) {
    invisible(.Call('_BDStatMethExamples_bdCCA_hdf5_rcpp', PACKAGE = 'BDStatMethExamples', filename, datasetX, datasetY, bcenter, bscale, overwrite, threads))
}

